language: node_js
node_js:
  - 8
install:
  - npm i
  - python3 -m pip install awscli
after_success:
  - npm run build
deploy:
  provider: script
  script: ./deploy.sh
  skip_cleanup: true
  on:
    branch: master
notifications:
  email: false