language: node_js
node_js:
  - 8
addons:
  apt:
    packages:
      - python3-pip
install:
  - npm i
  - pip3 install --user awscli
after_success:
  - npm run build
deploy:
  provider: script
  script: ./deploy.sh
  skip_cleanup: true
  on:
    branch: master
notifications:
  email: false